### PR TITLE
Updated instructions as requested with minor issues

### PR DESCRIPTION
**Pull request by nwl292**
I'm not sure how to get the arrow that shows up for other transitions, and I also do not know what the transition name is. Can someone clarify?

### CODE REVIEW

**Comment by larsvilhuber** [comment]
You copy and paste one of the other arrows. Easypeasy.

**Comment by larsvilhuber** [comment]
@nwl292  Also, don't forget to update instructions in https://github.com/labordynamicsinstitute/replicability-training/blob/master/jira-prepare-publication.md with details. You can add them to the same pull request.

**Comment by nwl292** [comment]
Thanks, what is the transition name for this status?

**Comment by larsvilhuber** [comment]
Transition name is "Waiting for ICPSR response"

**Pull request merged**
